"""reconcile schema documentation comments

Revision ID: e3f791aca64d
Revises: 088_precampaign_idempotency
Create Date: 2026-08-16 11:34:09.279345

Purpose:
    Keeps PostgreSQL table and column comments aligned with the SQLAlchemy
    metadata after documentation was rewritten to describe the current system.
    Alembic compares comments as schema, so metadata changes need a migration.

Forward migration:
    Updates only COMMENT values on affected tables and columns.

Rollback:
    Supported. Restores every previous table and column comment.

Data implications:
    None. PostgreSQL catalog descriptions change; application data does not.

Locking considerations:
    COMMENT statements take brief catalog-level locks and do not scan tables.

See: docs/DATABASE_CONVENTIONS.md §25.2 (Migration files)

NOTE: the revision id below must be 32 characters or fewer. Alembic's
core.alembic_version.version_num column is VARCHAR(32), and a longer id fails
only at the very end of the migration — after all the DDL has run — with
"value too long for type character varying(32)".
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e3f791aca64d"
down_revision = "088_precampaign_idempotency"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "change_log",
        "event_id",
        existing_type=sa.UUID(),
        comment="The narrative event that caused this change. Nullable for records that have no causal event.",
        existing_comment="The narrative event that caused this change, once narrative.events exists in Phase 6. Unconstrained until then; rule 6 in CLAUDE.md is what makes it matter.",
        existing_nullable=True,
        schema="audit",
    )
    op.create_table_comment(
        "campaigns",
        "A single game's run on a timeline. Several campaigns may share one timeline. Does not own world entities — it reaches them through participation, discovery, state, and event records.",
        existing_comment="A single game's run on a timeline. Several campaigns may share one timeline (docs/PLAN.md §5.3). Does not own world entities — it reaches them through participation, discovery, state, and event records.",
        schema="campaign",
    )
    op.create_table_comment(
        "character_conditions",
        "A condition currently active on a character in a timeline. source_description provides a free-text explanation; source_event_id identifies a causal event.",
        existing_comment="A condition currently active on a character in a timeline. source_description is free text for now — a causal event reference arrives in Phase 6.",
        schema="campaign",
    )
    op.create_table_comment(
        "character_location_history",
        "Where a character has been on a timeline. The row with departed_at_world_time_id IS NULL is the character's current location — the single current-location representation, enforced by the derived location_period range together with the ex_character_location_history_no_overlap exclusion constraint over (timeline_id, character_id, location_period), the same ADR 0010 shape as campaign.party_memberships. References world.locations (docs/architecture/DATABASE_MODEL.md §17).",
        existing_comment="Where a character has been on a timeline. The row with departed_at_world_time_id IS NULL is the character's current location — the single current-location representation, enforced by the derived location_period range together with the ex_character_location_history_no_overlap exclusion constraint over (timeline_id, character_id, location_period), the same ADR 0010 shape as campaign.party_memberships. Deferred from Phase 4 until world.locations existed (docs/architecture/DATABASE_MODEL.md §17).",
        schema="campaign",
    )
    op.create_table_comment(
        "parties",
        "A group of characters who adventure together. A stable world-level identity that may persist across campaigns; membership is timeline-scoped state, not a property of this row.",
        existing_comment="A group of characters who adventure together. A stable world-level identity that may persist across campaigns; membership is timeline-scoped state, not a property of this row (docs/PLAN.md §5.4).",
        schema="campaign",
    )
    op.create_table_comment(
        "party_knowledge",
        "The party's own current effective belief about a knowledge item on a timeline (docs/DOMAIN_MODEL.md §15.4) — distinct from knowledge.party_discoveries, which records only when/how the party acquired the item and carries no belief/confidence/interpretation of its own. Does not imply every party member shares this understanding unless the application explicitly promotes it to individual knowledge.entity_knowledge rows. A false belief is valid game data and is never overwritten merely because the canonical truth is known elsewhere — same rule as knowledge.entity_knowledge (revision 041). One row per (timeline, party, knowledge item).",
        existing_comment="The party's own current effective belief about a knowledge item on a timeline (docs/DOMAIN_MODEL.md §15.4, docs/PLAN.md §15) — distinct from knowledge.party_discoveries, which records only when/how the party acquired the item and carries no belief/confidence/interpretation of its own. Does not imply every party member shares this understanding unless the application explicitly promotes it to individual knowledge.entity_knowledge rows. A false belief is valid game data and is never overwritten merely because the canonical truth is known elsewhere — same rule as knowledge.entity_knowledge (revision 041). One row per (timeline, party, knowledge item).",
        schema="campaign",
    )
    op.alter_column(
        "party_memberships",
        "member_entity_id",
        existing_type=sa.UUID(),
        comment="References core.entities so membership identity remains polymorphic. Characters are entities, so this is correct but weaker than it will be — the database cannot yet reject a non-character being added to a party.",
        existing_comment="References core.entities, not character.characters, which arrives in Phase 4. Characters are entities, so this is correct but weaker than it will be — the database cannot yet reject a non-character being added to a party.",
        existing_nullable=False,
        schema="campaign",
    )
    op.create_table_comment(
        "relationship_state",
        "Tracks a relationship's current status for a timeline, optionally scoped to one perspective holder (docs/architecture/DATABASE_MODEL.md §17) — same perspective_holder_entity_id NULL/set convention as campaign.quest_state's party_id: NULL is the shared/objective status, set is that one participant's current subjective reaction (affinity, trust, respect, fear, obligation, emotional tone). This is the row events update as NPC and faction reactions evolve — unlike the stable, authored world.relationship_perspectives baseline. One current row per (timeline, relationship[, perspective holder]) — see the partial unique indexes below.",
        existing_comment="Tracks a relationship's current status for a timeline, optionally scoped to one perspective holder (docs/architecture/DATABASE_MODEL.md §17) — same perspective_holder_entity_id NULL/set convention as campaign.quest_state's party_id: NULL is the shared/objective status, set is that one participant's current subjective reaction (affinity, trust, respect, fear, obligation, emotional tone). This is the row events update — see docs/PLAN.md's \"NPC and faction reactions can evolve from events\" exit criterion — unlike the stable, authored world.relationship_perspectives baseline. One current row per (timeline, relationship[, perspective holder]) — see the partial unique indexes below.",
        schema="campaign",
    )
    op.alter_column(
        "sessions",
        "summary",
        existing_type=sa.TEXT(),
        comment="A derived artifact. May be revised freely without changing the events it summarizes.",
        existing_comment="A derived artifact. May be revised freely without changing the events it summarizes (docs/PLAN.md §5.5).",
        existing_nullable=True,
        schema="campaign",
    )
    op.create_table_comment(
        "sessions",
        "A single period of play within a campaign. Carries both real-world time (started_at/ended_at, when the table actually played) and fictional time (start/end_world_time_id, where the story was).",
        existing_comment="A single period of play within a campaign. Carries both real-world time (started_at/ended_at, when the table actually played) and fictional time (start/end_world_time_id, where the story was) — see docs/PLAN.md §5.5.",
        schema="campaign",
    )
    op.alter_column(
        "timelines",
        "branch_world_time_id",
        existing_type=sa.UUID(),
        comment="The world time at which this timeline diverged from its parent. NULL only for a root timeline. branch_event_id records the causal narrative event.",
        existing_comment="The world time at which this timeline diverged from its parent. NULL only for a root timeline. The causal branch_event_id arrives in Phase 6 with narrative.events.",
        existing_nullable=True,
        schema="campaign",
    )
    op.create_table_comment(
        "timelines",
        "A branching chronology within a world. Campaigns are played on a timeline; a branch inherits parent history only up to its branch point.",
        existing_comment="A branching chronology within a world. Campaigns are played on a timeline; a branch inherits parent history only up to its branch point (docs/PLAN.md §5.2).",
        schema="campaign",
    )
    op.create_table_comment(
        "character_descriptions",
        "Free-text background, appearance, and notes that do not drive mechanics. Optional: a character need not have one.",
        existing_comment="Free-text background, appearance, and notes that do not drive mechanics (docs/PLAN.md §7.2). Optional: a character need not have one yet.",
        schema="character",
    )
    op.alter_column(
        "characters",
        "origin_location_id",
        existing_type=sa.UUID(),
        comment="Where this character is from (docs/architecture/DATABASE_MODEL.md §7.1). The location must belong to the character's own world, enforced by trigger.",
        existing_comment="Where this character is from. Deferred from Phase 4 until world.locations existed (docs/architecture/DATABASE_MODEL.md §7.1). Must belong to the character's own world, enforced by trigger.",
        existing_nullable=True,
        schema="character",
    )
    op.create_table_comment(
        "characters",
        "Identity-level mechanical data shared by every character: species and size. NPCs and player characters both extend this row rather than duplicating it (docs/DOMAIN_MODEL.md §7.1). origin_location_id references world.locations.",
        existing_comment="Identity-level mechanical data shared by every character: species and size. NPCs and player characters both extend this row rather than duplicating it (docs/PLAN.md §7.1). origin_location_id arrives in Phase 5 once world.locations exists.",
        schema="character",
    )
    op.create_table_comment(
        "npcs",
        "Marks a character as an NPC. Portrayal, goals, routines, and other simulation apparatus belongs in the AI domain rather than this mechanical table.",
        existing_comment="Marks a character as an NPC. Portrayal, goals, routines, and other simulation apparatus (docs/PLAN.md §8) are deferred to Phase 10, which builds the AI agents that consume them.",
        schema="character",
    )
    op.create_table_comment(
        "player_characters",
        "Marks a character as player-controlled. player_user_id is basic ownership identity; timeline- or session-scoped control handoffs are represented by security.membership_character_relationships.",
        existing_comment="Marks a character as player-controlled. player_user_id is basic ownership identity; timeline- or session-scoped control handoffs (character.character_controllers) are deferred to Phase 10.",
        schema="character",
    )
    op.create_table_comment(
        "source_types",
        "Where an authored or imported fact came from.",
        existing_comment="Where an authored or imported fact came from — see docs/PLAN.md §4.5.",
        schema="core",
    )
    op.create_table_comment(
        "sources",
        "Where an authored or imported fact came from. Every meaningful authored record should reference one where practical.",
        existing_comment="Where an authored or imported fact came from. Every meaningful authored record should reference one where practical (docs/PLAN.md §4.5).",
        schema="core",
    )
    op.alter_column(
        "consequences",
        "resulting_quest_objective_state_id",
        existing_type=sa.UUID(),
        comment="The objective-state row produced by a quest_change consequence, when it has one.",
        existing_comment="The objective-state row a quest_change consequence produced, when it has one. Closes revision 061's own documented placeholder (\"quest_change ... consequence types have no FK target at all yet ... Phase 7/8 domains do not exist\") for its quest half; relationship_change remains Phase 8's job.",
        existing_nullable=True,
        schema="interaction",
    )
    op.alter_column(
        "consequences",
        "resulting_relationship_state_id",
        existing_type=sa.UUID(),
        comment="The relationship-state row produced by a relationship_change consequence, when it has one.",
        existing_comment='The relationship-state row a relationship_change consequence produced, when it has one. Closes revision 061\'s own documented placeholder ("relationship_change ... consequence types have no FK target at all yet ... Phase 7/8 domains do not exist") for its relationship half.',
        existing_nullable=True,
        schema="interaction",
    )
    op.alter_column(
        "knowledge_items",
        "sensitivity",
        existing_type=sa.TEXT(),
        comment="A fixed, universal classification (public, restricted, secret, dangerous), not a lookup, matching character.characters.size_category.",
        existing_comment="A fixed, universal classification (public, restricted, secret, dangerous), not a lookup — same reasoning as character.characters.size_category (Phase 4).",
        existing_nullable=False,
        existing_server_default=sa.text("'public'::text"),
        schema="knowledge",
    )
    op.create_table_comment(
        "party_discoveries",
        "The discovery record: when and how a party or individual knower learned a knowledge item (docs/architecture/DATABASE_MODEL.md §15). Recipient is exactly one of party_id (party-level discovery) or knower_entity_id (individual character, NPC, or organization discovery) — public/regional discovery is represented by knowledge.public_knowledge.",
        existing_comment="The discovery record: when and how a party or individual knower learned a knowledge item (docs/architecture/DATABASE_MODEL.md §15). Recipient is exactly one of party_id (party-level discovery) or knower_entity_id (individual character, NPC, or organization discovery) — public/regional discovery (knowledge.public_knowledge) is deferred to Phase 7.",
        schema="knowledge",
    )
    op.create_table_comment(
        "event_types",
        "The kind of occurrence an event represents. An illustrative, extensible starter set, not an exhaustive taxonomy.",
        existing_comment="The kind of occurrence an event represents. An illustrative, extensible starter set (docs/PLAN.md §13.3), not an exhaustive taxonomy.",
        schema="narrative",
    )
    op.alter_column(
        "quest_objectives",
        "completion_rule",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment='Structured completion-rule metadata, for example {"rule": "quantity_threshold", "threshold": 3} — distinct from completion_mode (automatic vs. GM-confirmed, i.e. who decides) and from quantity_required (a single scalar). NULL when the objective\'s completion condition needs no structured metadata beyond its type and target.',
        existing_comment='Structured completion-rule metadata (docs/PLAN.md §14.1) — e.g. {"rule": "quantity_threshold", "threshold": 3} — distinct from completion_mode (automatic vs. GM-confirmed, i.e. who decides) and from quantity_required (a single scalar). NULL when the objective\'s completion condition needs no structured metadata beyond its type and target.',
        existing_nullable=True,
        schema="narrative",
    )
    op.alter_column(
        "quest_objectives",
        "visibility_policy",
        existing_type=sa.TEXT(),
        comment="Whether and when this objective is shown to players — distinct from requirement_level='hidden' (whether the objective is mandatory for quest completion, not whether players can see it). An illustrative vocabulary rather than an exhaustive policy enumeration.",
        existing_comment="Whether and when this objective is shown to players (docs/PLAN.md §14.1) — distinct from requirement_level='hidden' (whether the objective is mandatory for quest completion, not whether players can see it). An inferred, illustrative vocabulary — docs/PLAN.md does not enumerate policy values, only the concept.",
        existing_nullable=False,
        existing_server_default=sa.text("'visible'::text"),
        schema="narrative",
    )
    op.create_table_comment(
        "quest_rewards",
        "A reward granted by a specific quest outcome. item/currency rewards have no typed target; reward_knowledge_item_id is the supported typed reward.",
        existing_comment="A reward granted by a specific quest outcome. item/currency rewards have no typed target yet (Phase 9's item domain does not exist); reward_knowledge_item_id is the one typed reward this phase can express.",
        schema="narrative",
    )
    op.create_table_comment(
        "conditions",
        "A status a character can be under (poisoned, prone, ...). Definitions only — campaign.character_conditions tracks who currently has one.",
        existing_comment="A status a character can be under (poisoned, prone, ...). Definitions only — campaign.character_conditions (Phase 4 timeline state) tracks who currently has one.",
        schema="rules",
    )
    op.create_table_comment(
        "resource_definitions",
        "A depletable/rechargeable resource kind (spell slot, ki point, rage use, ...). Definitions only — campaign.character_resources tracks current and maximum amounts.",
        existing_comment="A depletable/rechargeable resource kind (spell slot, ki point, rage use, ...). Definitions only — campaign.character_resources (Phase 4 timeline state) tracks current and maximum amounts.",
        schema="rules",
    )
    op.create_table_comment(
        "rulesets",
        'A named, edition-neutral rule-system family (e.g. "D&D 5e") — a specific edition or revision is recorded on rules.ruleset_versions.version_label and description, not here. Homebrew rulesets are ordinary rows here with their own source and canon status, not a separate structure.',
        existing_comment='A named, edition-neutral rule-system family (e.g. "D&D 5e") — a specific edition or revision is recorded on rules.ruleset_versions.version_label and description, not here. Homebrew rulesets are ordinary rows here with their own source and canon status (docs/PLAN.md §6.2) — not a separate structure.',
        schema="rules",
    )
    op.create_table_comment(
        "idempotent_requests",
        "Durable Idempotency-Key store for command endpoints so retries do not duplicate effects. One row reserves (actor_user_id, campaign_id, idempotency_key) for the lifetime of the reserving transaction; a rolled-back or failed command releases the key automatically because its INSERT is part of the same rolled-back transaction. See src/dnd_ai/api/idempotency.py.",
        existing_comment='Durable Idempotency-Key store for command endpoints (docs/PLAN.md §25 "retries do not duplicate effects"). One row reserves (actor_user_id, campaign_id, idempotency_key) for the lifetime of the reserving transaction; a rolled-back or failed command releases the key automatically because its INSERT is part of the same rolled-back transaction. See src/dnd_ai/api/idempotency.py.',
        schema="security",
    )
    op.create_table_comment(
        "resource_grants",
        "Explicit many-to-many access to a protected record, without an unenforced (resource_type, resource_id) polymorphic reference (docs/architecture/DATABASE_MODEL.md §19.6). Exactly one grantee column and exactly one typed target column are non-null. Scoped to the six supported target kinds (character, entity, knowledge item, quest, session, event) — source_document_id, ai_proposed_change_id, and import_job_id are added by the migration that introduces their target table (§19.6's own extension rule). Revocation closes a row (revoked_at set) rather than deleting it.",
        existing_comment="Explicit many-to-many access to a protected record, without an unenforced (resource_type, resource_id) polymorphic reference (docs/architecture/DATABASE_MODEL.md §19.6). Exactly one grantee column and exactly one typed target column are non-null. Scoped to the six target kinds the Phase 10 vertical slice needs (character, entity, knowledge item, quest, session, event) — source_document_id, ai_proposed_change_id, and import_job_id are added by the migration that introduces their target table (§19.6's own extension rule). Revocation closes a row (revoked_at set) rather than deleting it.",
        schema="security",
    )
    op.alter_column(
        "area_connections",
        "is_conditional",
        existing_type=sa.BOOLEAN(),
        comment="True for a conditional route — traversable only when some condition holds. required_check_kind (revision 064), when set, makes a check-gated condition machine-evaluable; quest- or state-gated conditions rely on condition_description.",
        existing_comment="True for a conditional route (docs/PLAN.md §9.2) — traversable only when some condition holds. required_check_kind (revision 064), when set, makes a check-gated condition machine-evaluable; quest-gated or state-gated conditions still rely on condition_description alone (Phase 7).",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
        schema="world",
    )
    op.create_table_comment(
        "businesses",
        "A business organization engaged in trade, services, or production (docs/DOMAIN_MODEL.md §10.3). Locations/employees/owners are expressed through world.organizations.headquarters_location_id and the employment/ownership specialized relationships, not duplicated here; inventory and prices belong to the item domain.",
        existing_comment="A business organization engaged in trade, services, or production (docs/DOMAIN_MODEL.md §10.3). Locations/employees/owners are expressed through world.organizations.headquarters_location_id and the employment/ownership specialized relationships, not duplicated here; inventory/prices are deferred to Phase 9's item domain.",
        schema="world",
    )
    op.create_table_comment(
        "governments",
        "A government organization (docs/DOMAIN_MODEL.md §10.1). Jurisdiction/territorial control is expressed through the universal relationship model (relationship_type = control), per a domain example, not a typed column here; offices/leaders are organization_memberships, agencies are child organizations (parent_organization_id).",
        existing_comment="A government organization (docs/DOMAIN_MODEL.md §10.1). Jurisdiction/territorial control is expressed through the universal relationship model (relationship_type = control), per docs/PLAN.md's own example, not a typed column here; offices/leaders are organization_memberships, agencies are child organizations (parent_organization_id).",
        schema="world",
    )
    op.create_table_comment(
        "ownership_relationships",
        "A specialized relationship: an entity owning another non-item entity — a business, a building, another organization (docs/architecture/DATABASE_MODEL.md §10.2). Item ownership stays with campaign.item_ownership rather than this table.",
        existing_comment="A specialized relationship: an entity owning another non-item entity — a business, a building, another organization (docs/architecture/DATABASE_MODEL.md §10.2). Item ownership stays with the future Phase 9 item domain (campaign.item_ownership) rather than this table.",
        schema="world",
    )
    op.create_table_comment(
        "religions",
        'A belief system, theology, or doctrine (docs/DOMAIN_MODEL.md §10.5) — distinct from a religious organization (a church, temple, order, or cult that serves it, world.religious_organizations, below). pantheon_structure is illustrative free text (monotheistic, polytheistic, pantheistic, animistic, philosophical, ...). Holy sites and reverence are expressed through the universal relationship model (the "religion reveres deity" relationship), not typed columns here; doctrines/rituals/sacred texts/symbols/traditions are descriptive lore carried by the inherited core.entities.summary and core.entity_names, with no exit criterion requiring structured columns for them yet.',
        existing_comment='A belief system, theology, or doctrine (docs/DOMAIN_MODEL.md §10.5) — distinct from a religious organization (a church, temple, order, or cult that serves it, world.religious_organizations, below). pantheon_structure is illustrative free text (monotheistic, polytheistic, pantheistic, animistic, philosophical, ...). Holy sites and reverence are expressed through the universal relationship model (docs/PLAN.md\'s own "religion reveres deity" example), not typed columns here; doctrines/rituals/sacred texts/symbols/traditions are descriptive lore carried by the inherited core.entities.summary and core.entity_names, with no exit criterion requiring structured columns for them yet.',
        schema="world",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        "religions",
        'A belief system, theology, or doctrine (docs/DOMAIN_MODEL.md §10.5) — distinct from a religious organization (a church, temple, order, or cult that serves it, world.religious_organizations, below). pantheon_structure is illustrative free text (monotheistic, polytheistic, pantheistic, animistic, philosophical, ...). Holy sites and reverence are expressed through the universal relationship model (docs/PLAN.md\'s own "religion reveres deity" example), not typed columns here; doctrines/rituals/sacred texts/symbols/traditions are descriptive lore carried by the inherited core.entities.summary and core.entity_names, with no exit criterion requiring structured columns for them yet.',
        existing_comment='A belief system, theology, or doctrine (docs/DOMAIN_MODEL.md §10.5) — distinct from a religious organization (a church, temple, order, or cult that serves it, world.religious_organizations, below). pantheon_structure is illustrative free text (monotheistic, polytheistic, pantheistic, animistic, philosophical, ...). Holy sites and reverence are expressed through the universal relationship model (the "religion reveres deity" relationship), not typed columns here; doctrines/rituals/sacred texts/symbols/traditions are descriptive lore carried by the inherited core.entities.summary and core.entity_names, with no exit criterion requiring structured columns for them yet.',
        schema="world",
    )
    op.create_table_comment(
        "ownership_relationships",
        "A specialized relationship: an entity owning another non-item entity — a business, a building, another organization (docs/architecture/DATABASE_MODEL.md §10.2). Item ownership stays with the future Phase 9 item domain (campaign.item_ownership) rather than this table.",
        existing_comment="A specialized relationship: an entity owning another non-item entity — a business, a building, another organization (docs/architecture/DATABASE_MODEL.md §10.2). Item ownership stays with campaign.item_ownership rather than this table.",
        schema="world",
    )
    op.create_table_comment(
        "governments",
        "A government organization (docs/DOMAIN_MODEL.md §10.1). Jurisdiction/territorial control is expressed through the universal relationship model (relationship_type = control), per docs/PLAN.md's own example, not a typed column here; offices/leaders are organization_memberships, agencies are child organizations (parent_organization_id).",
        existing_comment="A government organization (docs/DOMAIN_MODEL.md §10.1). Jurisdiction/territorial control is expressed through the universal relationship model (relationship_type = control), per a domain example, not a typed column here; offices/leaders are organization_memberships, agencies are child organizations (parent_organization_id).",
        schema="world",
    )
    op.create_table_comment(
        "businesses",
        "A business organization engaged in trade, services, or production (docs/DOMAIN_MODEL.md §10.3). Locations/employees/owners are expressed through world.organizations.headquarters_location_id and the employment/ownership specialized relationships, not duplicated here; inventory/prices are deferred to Phase 9's item domain.",
        existing_comment="A business organization engaged in trade, services, or production (docs/DOMAIN_MODEL.md §10.3). Locations/employees/owners are expressed through world.organizations.headquarters_location_id and the employment/ownership specialized relationships, not duplicated here; inventory and prices belong to the item domain.",
        schema="world",
    )
    op.alter_column(
        "area_connections",
        "is_conditional",
        existing_type=sa.BOOLEAN(),
        comment="True for a conditional route (docs/PLAN.md §9.2) — traversable only when some condition holds. required_check_kind (revision 064), when set, makes a check-gated condition machine-evaluable; quest-gated or state-gated conditions still rely on condition_description alone (Phase 7).",
        existing_comment="True for a conditional route — traversable only when some condition holds. required_check_kind (revision 064), when set, makes a check-gated condition machine-evaluable; quest- or state-gated conditions rely on condition_description.",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
        schema="world",
    )
    op.create_table_comment(
        "resource_grants",
        "Explicit many-to-many access to a protected record, without an unenforced (resource_type, resource_id) polymorphic reference (docs/architecture/DATABASE_MODEL.md §19.6). Exactly one grantee column and exactly one typed target column are non-null. Scoped to the six target kinds the Phase 10 vertical slice needs (character, entity, knowledge item, quest, session, event) — source_document_id, ai_proposed_change_id, and import_job_id are added by the migration that introduces their target table (§19.6's own extension rule). Revocation closes a row (revoked_at set) rather than deleting it.",
        existing_comment="Explicit many-to-many access to a protected record, without an unenforced (resource_type, resource_id) polymorphic reference (docs/architecture/DATABASE_MODEL.md §19.6). Exactly one grantee column and exactly one typed target column are non-null. Scoped to the six supported target kinds (character, entity, knowledge item, quest, session, event) — source_document_id, ai_proposed_change_id, and import_job_id are added by the migration that introduces their target table (§19.6's own extension rule). Revocation closes a row (revoked_at set) rather than deleting it.",
        schema="security",
    )
    op.create_table_comment(
        "idempotent_requests",
        'Durable Idempotency-Key store for command endpoints (docs/PLAN.md §25 "retries do not duplicate effects"). One row reserves (actor_user_id, campaign_id, idempotency_key) for the lifetime of the reserving transaction; a rolled-back or failed command releases the key automatically because its INSERT is part of the same rolled-back transaction. See src/dnd_ai/api/idempotency.py.',
        existing_comment="Durable Idempotency-Key store for command endpoints so retries do not duplicate effects. One row reserves (actor_user_id, campaign_id, idempotency_key) for the lifetime of the reserving transaction; a rolled-back or failed command releases the key automatically because its INSERT is part of the same rolled-back transaction. See src/dnd_ai/api/idempotency.py.",
        schema="security",
    )
    op.create_table_comment(
        "rulesets",
        'A named, edition-neutral rule-system family (e.g. "D&D 5e") — a specific edition or revision is recorded on rules.ruleset_versions.version_label and description, not here. Homebrew rulesets are ordinary rows here with their own source and canon status (docs/PLAN.md §6.2) — not a separate structure.',
        existing_comment='A named, edition-neutral rule-system family (e.g. "D&D 5e") — a specific edition or revision is recorded on rules.ruleset_versions.version_label and description, not here. Homebrew rulesets are ordinary rows here with their own source and canon status, not a separate structure.',
        schema="rules",
    )
    op.create_table_comment(
        "resource_definitions",
        "A depletable/rechargeable resource kind (spell slot, ki point, rage use, ...). Definitions only — campaign.character_resources (Phase 4 timeline state) tracks current and maximum amounts.",
        existing_comment="A depletable/rechargeable resource kind (spell slot, ki point, rage use, ...). Definitions only — campaign.character_resources tracks current and maximum amounts.",
        schema="rules",
    )
    op.create_table_comment(
        "conditions",
        "A status a character can be under (poisoned, prone, ...). Definitions only — campaign.character_conditions (Phase 4 timeline state) tracks who currently has one.",
        existing_comment="A status a character can be under (poisoned, prone, ...). Definitions only — campaign.character_conditions tracks who currently has one.",
        schema="rules",
    )
    op.create_table_comment(
        "quest_rewards",
        "A reward granted by a specific quest outcome. item/currency rewards have no typed target yet (Phase 9's item domain does not exist); reward_knowledge_item_id is the one typed reward this phase can express.",
        existing_comment="A reward granted by a specific quest outcome. item/currency rewards have no typed target; reward_knowledge_item_id is the supported typed reward.",
        schema="narrative",
    )
    op.alter_column(
        "quest_objectives",
        "visibility_policy",
        existing_type=sa.TEXT(),
        comment="Whether and when this objective is shown to players (docs/PLAN.md §14.1) — distinct from requirement_level='hidden' (whether the objective is mandatory for quest completion, not whether players can see it). An inferred, illustrative vocabulary — docs/PLAN.md does not enumerate policy values, only the concept.",
        existing_comment="Whether and when this objective is shown to players — distinct from requirement_level='hidden' (whether the objective is mandatory for quest completion, not whether players can see it). An illustrative vocabulary rather than an exhaustive policy enumeration.",
        existing_nullable=False,
        existing_server_default=sa.text("'visible'::text"),
        schema="narrative",
    )
    op.alter_column(
        "quest_objectives",
        "completion_rule",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment='Structured completion-rule metadata (docs/PLAN.md §14.1) — e.g. {"rule": "quantity_threshold", "threshold": 3} — distinct from completion_mode (automatic vs. GM-confirmed, i.e. who decides) and from quantity_required (a single scalar). NULL when the objective\'s completion condition needs no structured metadata beyond its type and target.',
        existing_comment='Structured completion-rule metadata, for example {"rule": "quantity_threshold", "threshold": 3} — distinct from completion_mode (automatic vs. GM-confirmed, i.e. who decides) and from quantity_required (a single scalar). NULL when the objective\'s completion condition needs no structured metadata beyond its type and target.',
        existing_nullable=True,
        schema="narrative",
    )
    op.create_table_comment(
        "event_types",
        "The kind of occurrence an event represents. An illustrative, extensible starter set (docs/PLAN.md §13.3), not an exhaustive taxonomy.",
        existing_comment="The kind of occurrence an event represents. An illustrative, extensible starter set, not an exhaustive taxonomy.",
        schema="narrative",
    )
    op.create_table_comment(
        "party_discoveries",
        "The discovery record: when and how a party or individual knower learned a knowledge item (docs/architecture/DATABASE_MODEL.md §15). Recipient is exactly one of party_id (party-level discovery) or knower_entity_id (individual character, NPC, or organization discovery) — public/regional discovery (knowledge.public_knowledge) is deferred to Phase 7.",
        existing_comment="The discovery record: when and how a party or individual knower learned a knowledge item (docs/architecture/DATABASE_MODEL.md §15). Recipient is exactly one of party_id (party-level discovery) or knower_entity_id (individual character, NPC, or organization discovery) — public/regional discovery is represented by knowledge.public_knowledge.",
        schema="knowledge",
    )
    op.alter_column(
        "knowledge_items",
        "sensitivity",
        existing_type=sa.TEXT(),
        comment="A fixed, universal classification (public, restricted, secret, dangerous), not a lookup — same reasoning as character.characters.size_category (Phase 4).",
        existing_comment="A fixed, universal classification (public, restricted, secret, dangerous), not a lookup, matching character.characters.size_category.",
        existing_nullable=False,
        existing_server_default=sa.text("'public'::text"),
        schema="knowledge",
    )
    op.alter_column(
        "consequences",
        "resulting_relationship_state_id",
        existing_type=sa.UUID(),
        comment='The relationship-state row a relationship_change consequence produced, when it has one. Closes revision 061\'s own documented placeholder ("relationship_change ... consequence types have no FK target at all yet ... Phase 7/8 domains do not exist") for its relationship half.',
        existing_comment="The relationship-state row produced by a relationship_change consequence, when it has one.",
        existing_nullable=True,
        schema="interaction",
    )
    op.alter_column(
        "consequences",
        "resulting_quest_objective_state_id",
        existing_type=sa.UUID(),
        comment="The objective-state row a quest_change consequence produced, when it has one. Closes revision 061's own documented placeholder (\"quest_change ... consequence types have no FK target at all yet ... Phase 7/8 domains do not exist\") for its quest half; relationship_change remains Phase 8's job.",
        existing_comment="The objective-state row produced by a quest_change consequence, when it has one.",
        existing_nullable=True,
        schema="interaction",
    )
    op.create_table_comment(
        "sources",
        "Where an authored or imported fact came from. Every meaningful authored record should reference one where practical (docs/PLAN.md §4.5).",
        existing_comment="Where an authored or imported fact came from. Every meaningful authored record should reference one where practical.",
        schema="core",
    )
    op.create_table_comment(
        "source_types",
        "Where an authored or imported fact came from — see docs/PLAN.md §4.5.",
        existing_comment="Where an authored or imported fact came from.",
        schema="core",
    )
    op.create_table_comment(
        "player_characters",
        "Marks a character as player-controlled. player_user_id is basic ownership identity; timeline- or session-scoped control handoffs (character.character_controllers) are deferred to Phase 10.",
        existing_comment="Marks a character as player-controlled. player_user_id is basic ownership identity; timeline- or session-scoped control handoffs are represented by security.membership_character_relationships.",
        schema="character",
    )
    op.create_table_comment(
        "npcs",
        "Marks a character as an NPC. Portrayal, goals, routines, and other simulation apparatus (docs/PLAN.md §8) are deferred to Phase 10, which builds the AI agents that consume them.",
        existing_comment="Marks a character as an NPC. Portrayal, goals, routines, and other simulation apparatus belongs in the AI domain rather than this mechanical table.",
        schema="character",
    )
    op.create_table_comment(
        "characters",
        "Identity-level mechanical data shared by every character: species and size. NPCs and player characters both extend this row rather than duplicating it (docs/PLAN.md §7.1). origin_location_id arrives in Phase 5 once world.locations exists.",
        existing_comment="Identity-level mechanical data shared by every character: species and size. NPCs and player characters both extend this row rather than duplicating it (docs/DOMAIN_MODEL.md §7.1). origin_location_id references world.locations.",
        schema="character",
    )
    op.alter_column(
        "characters",
        "origin_location_id",
        existing_type=sa.UUID(),
        comment="Where this character is from. Deferred from Phase 4 until world.locations existed (docs/architecture/DATABASE_MODEL.md §7.1). Must belong to the character's own world, enforced by trigger.",
        existing_comment="Where this character is from (docs/architecture/DATABASE_MODEL.md §7.1). The location must belong to the character's own world, enforced by trigger.",
        existing_nullable=True,
        schema="character",
    )
    op.create_table_comment(
        "character_descriptions",
        "Free-text background, appearance, and notes that do not drive mechanics (docs/PLAN.md §7.2). Optional: a character need not have one yet.",
        existing_comment="Free-text background, appearance, and notes that do not drive mechanics. Optional: a character need not have one.",
        schema="character",
    )
    op.create_table_comment(
        "timelines",
        "A branching chronology within a world. Campaigns are played on a timeline; a branch inherits parent history only up to its branch point (docs/PLAN.md §5.2).",
        existing_comment="A branching chronology within a world. Campaigns are played on a timeline; a branch inherits parent history only up to its branch point.",
        schema="campaign",
    )
    op.alter_column(
        "timelines",
        "branch_world_time_id",
        existing_type=sa.UUID(),
        comment="The world time at which this timeline diverged from its parent. NULL only for a root timeline. The causal branch_event_id arrives in Phase 6 with narrative.events.",
        existing_comment="The world time at which this timeline diverged from its parent. NULL only for a root timeline. branch_event_id records the causal narrative event.",
        existing_nullable=True,
        schema="campaign",
    )
    op.create_table_comment(
        "sessions",
        "A single period of play within a campaign. Carries both real-world time (started_at/ended_at, when the table actually played) and fictional time (start/end_world_time_id, where the story was) — see docs/PLAN.md §5.5.",
        existing_comment="A single period of play within a campaign. Carries both real-world time (started_at/ended_at, when the table actually played) and fictional time (start/end_world_time_id, where the story was).",
        schema="campaign",
    )
    op.alter_column(
        "sessions",
        "summary",
        existing_type=sa.TEXT(),
        comment="A derived artifact. May be revised freely without changing the events it summarizes (docs/PLAN.md §5.5).",
        existing_comment="A derived artifact. May be revised freely without changing the events it summarizes.",
        existing_nullable=True,
        schema="campaign",
    )
    op.create_table_comment(
        "relationship_state",
        "Tracks a relationship's current status for a timeline, optionally scoped to one perspective holder (docs/architecture/DATABASE_MODEL.md §17) — same perspective_holder_entity_id NULL/set convention as campaign.quest_state's party_id: NULL is the shared/objective status, set is that one participant's current subjective reaction (affinity, trust, respect, fear, obligation, emotional tone). This is the row events update — see docs/PLAN.md's \"NPC and faction reactions can evolve from events\" exit criterion — unlike the stable, authored world.relationship_perspectives baseline. One current row per (timeline, relationship[, perspective holder]) — see the partial unique indexes below.",
        existing_comment="Tracks a relationship's current status for a timeline, optionally scoped to one perspective holder (docs/architecture/DATABASE_MODEL.md §17) — same perspective_holder_entity_id NULL/set convention as campaign.quest_state's party_id: NULL is the shared/objective status, set is that one participant's current subjective reaction (affinity, trust, respect, fear, obligation, emotional tone). This is the row events update as NPC and faction reactions evolve — unlike the stable, authored world.relationship_perspectives baseline. One current row per (timeline, relationship[, perspective holder]) — see the partial unique indexes below.",
        schema="campaign",
    )
    op.alter_column(
        "party_memberships",
        "member_entity_id",
        existing_type=sa.UUID(),
        comment="References core.entities, not character.characters, which arrives in Phase 4. Characters are entities, so this is correct but weaker than it will be — the database cannot yet reject a non-character being added to a party.",
        existing_comment="References core.entities so membership identity remains polymorphic. Characters are entities, so this is correct but weaker than it will be — the database cannot yet reject a non-character being added to a party.",
        existing_nullable=False,
        schema="campaign",
    )
    op.create_table_comment(
        "party_knowledge",
        "The party's own current effective belief about a knowledge item on a timeline (docs/DOMAIN_MODEL.md §15.4, docs/PLAN.md §15) — distinct from knowledge.party_discoveries, which records only when/how the party acquired the item and carries no belief/confidence/interpretation of its own. Does not imply every party member shares this understanding unless the application explicitly promotes it to individual knowledge.entity_knowledge rows. A false belief is valid game data and is never overwritten merely because the canonical truth is known elsewhere — same rule as knowledge.entity_knowledge (revision 041). One row per (timeline, party, knowledge item).",
        existing_comment="The party's own current effective belief about a knowledge item on a timeline (docs/DOMAIN_MODEL.md §15.4) — distinct from knowledge.party_discoveries, which records only when/how the party acquired the item and carries no belief/confidence/interpretation of its own. Does not imply every party member shares this understanding unless the application explicitly promotes it to individual knowledge.entity_knowledge rows. A false belief is valid game data and is never overwritten merely because the canonical truth is known elsewhere — same rule as knowledge.entity_knowledge (revision 041). One row per (timeline, party, knowledge item).",
        schema="campaign",
    )
    op.create_table_comment(
        "parties",
        "A group of characters who adventure together. A stable world-level identity that may persist across campaigns; membership is timeline-scoped state, not a property of this row (docs/PLAN.md §5.4).",
        existing_comment="A group of characters who adventure together. A stable world-level identity that may persist across campaigns; membership is timeline-scoped state, not a property of this row.",
        schema="campaign",
    )
    op.create_table_comment(
        "character_location_history",
        "Where a character has been on a timeline. The row with departed_at_world_time_id IS NULL is the character's current location — the single current-location representation, enforced by the derived location_period range together with the ex_character_location_history_no_overlap exclusion constraint over (timeline_id, character_id, location_period), the same ADR 0010 shape as campaign.party_memberships. Deferred from Phase 4 until world.locations existed (docs/architecture/DATABASE_MODEL.md §17).",
        existing_comment="Where a character has been on a timeline. The row with departed_at_world_time_id IS NULL is the character's current location — the single current-location representation, enforced by the derived location_period range together with the ex_character_location_history_no_overlap exclusion constraint over (timeline_id, character_id, location_period), the same ADR 0010 shape as campaign.party_memberships. References world.locations (docs/architecture/DATABASE_MODEL.md §17).",
        schema="campaign",
    )
    op.create_table_comment(
        "character_conditions",
        "A condition currently active on a character in a timeline. source_description is free text for now — a causal event reference arrives in Phase 6.",
        existing_comment="A condition currently active on a character in a timeline. source_description provides a free-text explanation; source_event_id identifies a causal event.",
        schema="campaign",
    )
    op.create_table_comment(
        "campaigns",
        "A single game's run on a timeline. Several campaigns may share one timeline (docs/PLAN.md §5.3). Does not own world entities — it reaches them through participation, discovery, state, and event records.",
        existing_comment="A single game's run on a timeline. Several campaigns may share one timeline. Does not own world entities — it reaches them through participation, discovery, state, and event records.",
        schema="campaign",
    )
    op.alter_column(
        "change_log",
        "event_id",
        existing_type=sa.UUID(),
        comment="The narrative event that caused this change, once narrative.events exists in Phase 6. Unconstrained until then; rule 6 in CLAUDE.md is what makes it matter.",
        existing_comment="The narrative event that caused this change. Nullable for records that have no causal event.",
        existing_nullable=True,
        schema="audit",
    )
    # ### end Alembic commands ###
